### ISSUE TITLE
 Identifier 'PORT' has already been declared

### ISSUE THREAD

**Issue by blumareks** [lidderupk/nodejs-docker#4]
/data/translator-app/server.js:11
const PORT = process.env.PORT || 3000;
      ^

SyntaxError: Identifier 'PORT' has already been declared
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by blumareks** [comment]
it is enough to comment  the line 11:
`//const PORT = process.env.PORT || 3000;`

**Comment by stevemar** [comment]
Closed via #5 and #6
